services:
  openvpn:
    privileged: true
    build: ./
    volumes:
      - type: volume
        source: config
        target: /config
      - type: volume
        source: app
        target: /app
      - type: bind
        source: /run/media/neil/F71C-FB61/downloads/
        target: /downloads
    ports:
      - 8080:8080
      - 8080:8080/udp
      - 8999:8999
      - 8999:8999/udp
      - 9696:9696
      - 9696:9696/udp
    environment:
      VPN_ENABLED: "yes"
      LAN_NETWORK: "192.168.1.0/24"
      NAME_SERVERS: "8.8.8.8,8.8.4.4"

volumes:
  config:
  app:
